### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by varys50** [MolecularAI/Qptuna#1]
There seems to be some missing files like optunaz/algorithms.py

**Comment by jeremycheminf** [comment]
May be they are not all uploaded yet, the import from the doc on using python is also failing with can't import optunaz.utils.preprocessing.transform , there is no transform.py file.

**Comment by lewismervin1** [comment]
@varys50  @jeremycheminf  thank you for interest in Qptuna and opening the issue. I have now made all files available

**Comment by jeremycheminf** [comment]
Thank you
